"use client";
import { Layout, Menu } from "antd";
import "./globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { QueryClientProvider, QueryClient } from "react-query";
import { ConfigProvider, theme } from "antd";
import { HeaderComponent, LayoutComponent } from "@/components";
import { GlobalDataProvider } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <html lang="en">
      <SessionProvider>
        <GlobalDataProvider>
          <QueryClientProvider client={queryClient}>
            <ConfigProvider
              theme={{
                algorithm: theme.darkAlgorithm,
                token: {
                  colorPrimary: "#00fff1",
                },
                components: {
                  Layout: {
                    colorBgHeader: "#141516",
                    colorBgBody: "#141516",
                  },
                },
              }}
            >
              <body
                className={`${inter.className} text-white`}
                style={{
                  background: colorBgContainer,
                }}
              >
                <LayoutComponent>{children}</LayoutComponent>
              </body>
            </ConfigProvider>
          </QueryClientProvider>
        </GlobalDataProvider>
      </SessionProvider>
    </html>
  );
}
